import { VerticalBox, ComboBox } from "std-widgets.slint";
import { CameraDeviceViewData } from "types.slint";

export component CameraSelection inherits Rectangle {
    in-out property <int> selected-camera: -1;
    callback camera-selected(int);

    background: #202020;
    border-radius: 8px;


    in property <[string]> camera-names;

    ComboBox {
        model: root.camera-names;
        selected(value) => {
            let camera = root.camera-names[self.current-index];
            debug(camera-names);
            root.selected-camera = self.current-index;
            root.camera-selected(self.current-index);
        }
    }
}
