import {
    VerticalBox
} from "std-widgets.slint";
import {SText} from "composant.slint";

export component DataMetrics inherits Rectangle {
    in property <int> impact_count;
    in property <string> grouping_diameter;
    in property <string> grouping_widht;
    in property <string> grouping_height;
    in property <string> grouping_offset;
    in property <string> grouping_center;
    in property <string> average-impact-offset;
    in property <string> grouping_es;

    background: #181818;
    border-radius: 6px;

    VerticalBox {
        padding: 8px;
        spacing: 4px;

        Number-Shoot := SText {
            text: "Nombre : " + impact_count;
        }

        Group-Offset := SText {
            text: "Décalage cercle : " + grouping-offset;
        }

        PMI := SText {
            text: "Point moyen d'impact : " + average-impact-offset;
            wrap: word-wrap;
        }

        Dispersion := SText {
            text: "Dispersion : " + grouping-diameter;
        }

        Point-Vise := SText {
            text: "Écart au point visé : " + grouping-center;
        }
        SText {
        text: "Largeur : " + grouping_widht;
        }
        SText {
        text: "Hauteur : " + grouping_height;
        }
    }
}
