import {
    VerticalBox,
    HorizontalBox,
    Button,
    LineEdit,
    GridBox,
} from "std-widgets.slint";
import {SText} from "composant.slint";

export component ShootConfiguration inherits Rectangle {

    in-out property <float> target-distance: 100.0;
    in-out property <float> calibration-horizontal-distance: 100.0;
    in-out property <float> calibration-vertical-distance: 100.0;

    in property <bool> calibration-complete: false;
    in property <string> calibration-step: "Aucune";
    in property <string> calibration-instruction: "Cliquez sur \"Calibrer la cible\" pour démarrer.";

    callback request-calibration();
    callback cancel-calibration();
    callback calibration-distances-validated();
    callback target-distance-validated();

    background: #202020;
    border-radius: 8px;

    GridBox {
        spacing-vertical: 2px;
        Text {
            color: white;
            text: "Distance :";
            vertical-alignment: center;
        }

        target-distance-input := LineEdit {
            horizontal-stretch: 1;
            text: root.target-distance;
            placeholder-text: "Distance de tir en m";
            colspan: 2;
            accepted => {
                let value = self.text.to-float();

                if value > 0 {
                    root.target-distance = value;
                    root.target-distance-validated();
                }
            }
        }

        SText {
            text: "X :";
            vertical-alignment: center;
        }

        horizontal-distance-input := LineEdit {
            placeholder-text: "Distance en mm";
            horizontal-stretch: 1;
            text: root.calibration-horizontal-distance;

            accepted => {
                let value = self.text.to-float();

                if value > 0 {
                    root.calibration-horizontal-distance = value;
                    root.calibration-distances-validated();
                }
            }
        }

        SText {
            text: "Y :";
            vertical-alignment: center;
        }

        vertical-distance-input := LineEdit {
            placeholder-text: "Distance en mm";
            horizontal-stretch: 1;
            text: root.calibration-vertical-distance;

            accepted => {
                let value = self.text.to-float();

                if value > 0 {
                    root.calibration-vertical-distance = value;
                    root.calibration-distances-validated();
                }
            }
        }

        Button {
            text: "Valider";

            clicked => {
                let value = target-distance-input.text.to-float();

                if value > 0 {
                    root.target-distance = value;
                    root.target-distance-validated();
                }
                let horizontal-value = horizontal-distance-input.text.to-float();
                let vertical-value = vertical-distance-input.text.to-float();

                if horizontal-value > 0 && vertical-value > 0 {
                    root.calibration-horizontal-distance = horizontal-value;
                    root.calibration-vertical-distance = vertical-value;
                    root.calibration-distances-validated();
                }
            }
        }

        Button {
            text: calibration-complete
                ? "Annuler"
                : "Calibrer la cible";

            clicked => {
                root.request-calibration();
            }
        }
    }
}
